FROM node:18

# Create app directory
WORKDIR /src

# Copy required config files
COPY src/package*.json ./

COPY src/tsconfig.json ./

COPY src/.env ./

# Install app dependencies
RUN npm install

# Copy app source to the image
COPY . .

# Expose the app on port 5001
EXPOSE 5001

# Command to run the application
CMD ["npm", "start"]
