apiVersion: v1
kind: Secret
metadata:
  name: firebase-secret
type: Opaque
data:
  apiKey: QUl6YVN5QlUxejAxU2VYYXAtemlnam0wYUVGNHIxRDQ1SFU1R25Z
  authDomain: Y3MzMjE5LWc1Ni5maXJlYmFzZWFwcC5jb20=
  projectId: Y3MzMjE5LWc1Ng==
  storageBucket: Y3MzMjE5LWc1Ni5hcHBzcG90LmNvbQ==
  messagingSenderId: MTQxNzMzMDYwMDc0
  appId: MToxNDE3MzMwNjAwNzQ6d2ViOjNkNTU2MjA5NmUzNThkYTU5YzY2OTM=
  measurementId: Ry01MDBWWDVTQ0I1